//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.2-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.03.27 at 09:51:27 AM PDT 
//


package org.ngbw.sdk.bioutils.blast.blastxml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.ngbw.org/conversion/impl/blastxml}Iteration_iter-num"/>
 *         &lt;element ref="{http://www.ngbw.org/conversion/impl/blastxml}Iteration_hits"/>
 *         &lt;element ref="{http://www.ngbw.org/conversion/impl/blastxml}Iteration_stat"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "iterationIterNum",
    "iterationHits",
    "iterationStat"
})
@XmlRootElement(name = "Iteration")
public class Iteration {

    @XmlElement(name = "Iteration_iter-num", required = true)
    protected IterationIterNum iterationIterNum;
    @XmlElement(name = "Iteration_hits", required = true)
    protected IterationHits iterationHits;
    @XmlElement(name = "Iteration_stat", required = true)
    protected IterationStat iterationStat;

    /**
     * Gets the value of the iterationIterNum property.
     * 
     * @return
     *     possible object is
     *     {@link IterationIterNum }
     *     
     */
    public IterationIterNum getIterationIterNum() {
        return iterationIterNum;
    }

    /**
     * Sets the value of the iterationIterNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link IterationIterNum }
     *     
     */
    public void setIterationIterNum(IterationIterNum value) {
        this.iterationIterNum = value;
    }

    /**
     * Gets the value of the iterationHits property.
     * 
     * @return
     *     possible object is
     *     {@link IterationHits }
     *     
     */
    public IterationHits getIterationHits() {
        return iterationHits;
    }

    /**
     * Sets the value of the iterationHits property.
     * 
     * @param value
     *     allowed object is
     *     {@link IterationHits }
     *     
     */
    public void setIterationHits(IterationHits value) {
        this.iterationHits = value;
    }

    /**
     * Gets the value of the iterationStat property.
     * 
     * @return
     *     possible object is
     *     {@link IterationStat }
     *     
     */
    public IterationStat getIterationStat() {
        return iterationStat;
    }

    /**
     * Sets the value of the iterationStat property.
     * 
     * @param value
     *     allowed object is
     *     {@link IterationStat }
     *     
     */
    public void setIterationStat(IterationStat value) {
        this.iterationStat = value;
    }

}
