/*
 * RecordType.java
 */
package org.ngbw.sdk.core.types;


/**
 * a combination of EntityType and DataType
 * 
 * @author Roland H. Niedner
 * @author Paul Hoover
 *
 */
public enum RecordType {
	COMPOUND_STRUCTURE,
	CONTINUOUS_CHARACTER_MATRIX,
	DISCRETE_CHARACTER_MATRIX,
	MACROMOLECULE_BLAST_OUTPUT,
	MACROMOLECULE_FASTA_OUTPUT,
	MACROMOLECULE_SEQUENCE,
	MACROMOLECULE_SEQUENCE_ALIGNMENT,
	NUCLEIC_ACID_BLAST_OUTPUT,
	NUCLEIC_ACID_FASTA_OUTPUT,
	NUCLEIC_ACID_PHYLOGENETIC_TREE,
	NUCLEIC_ACID_SEQUENCE,
	NUCLEIC_ACID_SEQUENCE_ALIGNMENT,
	NUCLEIC_ACID_SIMILARITY_SEARCH_HIT,
	NUCLEIC_ACID_STRUCTURE,
	PROTEIN_BLAST_OUTPUT,
	PROTEIN_FASTA_OUTPUT,
	PROTEIN_PHYLOGENETIC_TREE,
	PROTEIN_SEQUENCE,
	PROTEIN_SEQUENCE_ALIGNMENT,
	PROTEIN_SIMILARITY_SEARCH_HIT,
	PROTEIN_STRUCTURE,
	PROTEIN_STRUCTURE_CHAIN_SIMILARITY_SEARCH_HIT,
	SERIALIZED_APPLICATION_DATA,
	TAXON_PHYLOGENETIC_TREE,
	UNKNOWN
}
