//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.2-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.03.27 at 09:51:27 AM PDT 
//


package org.ngbw.sdk.bioutils.blast.blastxml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.ngbw.org/conversion/impl/blastxml}Hit_num"/>
 *         &lt;element ref="{http://www.ngbw.org/conversion/impl/blastxml}Hit_id"/>
 *         &lt;element ref="{http://www.ngbw.org/conversion/impl/blastxml}Hit_def"/>
 *         &lt;element ref="{http://www.ngbw.org/conversion/impl/blastxml}Hit_accession"/>
 *         &lt;element ref="{http://www.ngbw.org/conversion/impl/blastxml}Hit_len"/>
 *         &lt;element ref="{http://www.ngbw.org/conversion/impl/blastxml}Hit_hsps"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "hitNum",
    "hitId",
    "hitDef",
    "hitAccession",
    "hitLen",
    "hitHsps"
})
@XmlRootElement(name = "Hit")
public class Hit {

    @XmlElement(name = "Hit_num", required = true)
    protected HitNum hitNum;
    @XmlElement(name = "Hit_id", required = true)
    protected HitId hitId;
    @XmlElement(name = "Hit_def", required = true)
    protected HitDef hitDef;
    @XmlElement(name = "Hit_accession", required = true)
    protected HitAccession hitAccession;
    @XmlElement(name = "Hit_len", required = true)
    protected HitLen hitLen;
    @XmlElement(name = "Hit_hsps", required = true)
    protected HitHsps hitHsps;

    /**
     * Gets the value of the hitNum property.
     * 
     * @return
     *     possible object is
     *     {@link HitNum }
     *     
     */
    public HitNum getHitNum() {
        return hitNum;
    }

    /**
     * Sets the value of the hitNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link HitNum }
     *     
     */
    public void setHitNum(HitNum value) {
        this.hitNum = value;
    }

    /**
     * Gets the value of the hitId property.
     * 
     * @return
     *     possible object is
     *     {@link HitId }
     *     
     */
    public HitId getHitId() {
        return hitId;
    }

    /**
     * Sets the value of the hitId property.
     * 
     * @param value
     *     allowed object is
     *     {@link HitId }
     *     
     */
    public void setHitId(HitId value) {
        this.hitId = value;
    }

    /**
     * Gets the value of the hitDef property.
     * 
     * @return
     *     possible object is
     *     {@link HitDef }
     *     
     */
    public HitDef getHitDef() {
        return hitDef;
    }

    /**
     * Sets the value of the hitDef property.
     * 
     * @param value
     *     allowed object is
     *     {@link HitDef }
     *     
     */
    public void setHitDef(HitDef value) {
        this.hitDef = value;
    }

    /**
     * Gets the value of the hitAccession property.
     * 
     * @return
     *     possible object is
     *     {@link HitAccession }
     *     
     */
    public HitAccession getHitAccession() {
        return hitAccession;
    }

    /**
     * Sets the value of the hitAccession property.
     * 
     * @param value
     *     allowed object is
     *     {@link HitAccession }
     *     
     */
    public void setHitAccession(HitAccession value) {
        this.hitAccession = value;
    }

    /**
     * Gets the value of the hitLen property.
     * 
     * @return
     *     possible object is
     *     {@link HitLen }
     *     
     */
    public HitLen getHitLen() {
        return hitLen;
    }

    /**
     * Sets the value of the hitLen property.
     * 
     * @param value
     *     allowed object is
     *     {@link HitLen }
     *     
     */
    public void setHitLen(HitLen value) {
        this.hitLen = value;
    }

    /**
     * Gets the value of the hitHsps property.
     * 
     * @return
     *     possible object is
     *     {@link HitHsps }
     *     
     */
    public HitHsps getHitHsps() {
        return hitHsps;
    }

    /**
     * Sets the value of the hitHsps property.
     * 
     * @param value
     *     allowed object is
     *     {@link HitHsps }
     *     
     */
    public void setHitHsps(HitHsps value) {
        this.hitHsps = value;
    }

}
