//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.2-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.03.27 at 09:51:27 AM PDT 
//


package org.ngbw.sdk.bioutils.blast.blastxml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.ngbw.org/conversion/impl/blastxml}BlastOutput_program"/>
 *         &lt;element ref="{http://www.ngbw.org/conversion/impl/blastxml}BlastOutput_version"/>
 *         &lt;element ref="{http://www.ngbw.org/conversion/impl/blastxml}BlastOutput_reference"/>
 *         &lt;element ref="{http://www.ngbw.org/conversion/impl/blastxml}BlastOutput_db"/>
 *         &lt;element ref="{http://www.ngbw.org/conversion/impl/blastxml}BlastOutput_query-ID"/>
 *         &lt;element ref="{http://www.ngbw.org/conversion/impl/blastxml}BlastOutput_query-def"/>
 *         &lt;element ref="{http://www.ngbw.org/conversion/impl/blastxml}BlastOutput_query-len"/>
 *         &lt;element ref="{http://www.ngbw.org/conversion/impl/blastxml}BlastOutput_param"/>
 *         &lt;element ref="{http://www.ngbw.org/conversion/impl/blastxml}BlastOutput_iterations"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "blastOutputProgram",
    "blastOutputVersion",
    "blastOutputReference",
    "blastOutputDb",
    "blastOutputQueryID",
    "blastOutputQueryDef",
    "blastOutputQueryLen",
    "blastOutputParam",
    "blastOutputIterations"
})
@XmlRootElement(name = "BlastOutput")
public class BlastOutput {

    @XmlElement(name = "BlastOutput_program", required = true)
    protected BlastOutputProgram blastOutputProgram;
    @XmlElement(name = "BlastOutput_version", required = true)
    protected BlastOutputVersion blastOutputVersion;
    @XmlElement(name = "BlastOutput_reference", required = true)
    protected BlastOutputReference blastOutputReference;
    @XmlElement(name = "BlastOutput_db", required = true)
    protected BlastOutputDb blastOutputDb;
    @XmlElement(name = "BlastOutput_query-ID", required = true)
    protected BlastOutputQueryID blastOutputQueryID;
    @XmlElement(name = "BlastOutput_query-def", required = true)
    protected BlastOutputQueryDef blastOutputQueryDef;
    @XmlElement(name = "BlastOutput_query-len", required = true)
    protected BlastOutputQueryLen blastOutputQueryLen;
    @XmlElement(name = "BlastOutput_param", required = true)
    protected BlastOutputParam blastOutputParam;
    @XmlElement(name = "BlastOutput_iterations", required = true)
    protected BlastOutputIterations blastOutputIterations;

    /**
     * Gets the value of the blastOutputProgram property.
     * 
     * @return
     *     possible object is
     *     {@link BlastOutputProgram }
     *     
     */
    public BlastOutputProgram getBlastOutputProgram() {
        return blastOutputProgram;
    }

    /**
     * Sets the value of the blastOutputProgram property.
     * 
     * @param value
     *     allowed object is
     *     {@link BlastOutputProgram }
     *     
     */
    public void setBlastOutputProgram(BlastOutputProgram value) {
        this.blastOutputProgram = value;
    }

    /**
     * Gets the value of the blastOutputVersion property.
     * 
     * @return
     *     possible object is
     *     {@link BlastOutputVersion }
     *     
     */
    public BlastOutputVersion getBlastOutputVersion() {
        return blastOutputVersion;
    }

    /**
     * Sets the value of the blastOutputVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link BlastOutputVersion }
     *     
     */
    public void setBlastOutputVersion(BlastOutputVersion value) {
        this.blastOutputVersion = value;
    }

    /**
     * Gets the value of the blastOutputReference property.
     * 
     * @return
     *     possible object is
     *     {@link BlastOutputReference }
     *     
     */
    public BlastOutputReference getBlastOutputReference() {
        return blastOutputReference;
    }

    /**
     * Sets the value of the blastOutputReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link BlastOutputReference }
     *     
     */
    public void setBlastOutputReference(BlastOutputReference value) {
        this.blastOutputReference = value;
    }

    /**
     * Gets the value of the blastOutputDb property.
     * 
     * @return
     *     possible object is
     *     {@link BlastOutputDb }
     *     
     */
    public BlastOutputDb getBlastOutputDb() {
        return blastOutputDb;
    }

    /**
     * Sets the value of the blastOutputDb property.
     * 
     * @param value
     *     allowed object is
     *     {@link BlastOutputDb }
     *     
     */
    public void setBlastOutputDb(BlastOutputDb value) {
        this.blastOutputDb = value;
    }

    /**
     * Gets the value of the blastOutputQueryID property.
     * 
     * @return
     *     possible object is
     *     {@link BlastOutputQueryID }
     *     
     */
    public BlastOutputQueryID getBlastOutputQueryID() {
        return blastOutputQueryID;
    }

    /**
     * Sets the value of the blastOutputQueryID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BlastOutputQueryID }
     *     
     */
    public void setBlastOutputQueryID(BlastOutputQueryID value) {
        this.blastOutputQueryID = value;
    }

    /**
     * Gets the value of the blastOutputQueryDef property.
     * 
     * @return
     *     possible object is
     *     {@link BlastOutputQueryDef }
     *     
     */
    public BlastOutputQueryDef getBlastOutputQueryDef() {
        return blastOutputQueryDef;
    }

    /**
     * Sets the value of the blastOutputQueryDef property.
     * 
     * @param value
     *     allowed object is
     *     {@link BlastOutputQueryDef }
     *     
     */
    public void setBlastOutputQueryDef(BlastOutputQueryDef value) {
        this.blastOutputQueryDef = value;
    }

    /**
     * Gets the value of the blastOutputQueryLen property.
     * 
     * @return
     *     possible object is
     *     {@link BlastOutputQueryLen }
     *     
     */
    public BlastOutputQueryLen getBlastOutputQueryLen() {
        return blastOutputQueryLen;
    }

    /**
     * Sets the value of the blastOutputQueryLen property.
     * 
     * @param value
     *     allowed object is
     *     {@link BlastOutputQueryLen }
     *     
     */
    public void setBlastOutputQueryLen(BlastOutputQueryLen value) {
        this.blastOutputQueryLen = value;
    }

    /**
     * Gets the value of the blastOutputParam property.
     * 
     * @return
     *     possible object is
     *     {@link BlastOutputParam }
     *     
     */
    public BlastOutputParam getBlastOutputParam() {
        return blastOutputParam;
    }

    /**
     * Sets the value of the blastOutputParam property.
     * 
     * @param value
     *     allowed object is
     *     {@link BlastOutputParam }
     *     
     */
    public void setBlastOutputParam(BlastOutputParam value) {
        this.blastOutputParam = value;
    }

    /**
     * Gets the value of the blastOutputIterations property.
     * 
     * @return
     *     possible object is
     *     {@link BlastOutputIterations }
     *     
     */
    public BlastOutputIterations getBlastOutputIterations() {
        return blastOutputIterations;
    }

    /**
     * Sets the value of the blastOutputIterations property.
     * 
     * @param value
     *     allowed object is
     *     {@link BlastOutputIterations }
     *     
     */
    public void setBlastOutputIterations(BlastOutputIterations value) {
        this.blastOutputIterations = value;
    }

}
