//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.2-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.03.28 at 05:22:06 PM PDT 
//


package org.ngbw.pise.commandrenderer.pise;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Vdef }
     * 
     */
    public Vdef createVdef() {
        return new Vdef();
    }

    /**
     * Create an instance of {@link Head }
     * 
     */
    public Head createHead() {
        return new Head();
    }

    /**
     * Create an instance of {@link Prompt }
     * 
     */
    public Prompt createPrompt() {
        return new Prompt();
    }

    /**
     * Create an instance of {@link Attributes }
     * 
     */
    public Attributes createAttributes() {
        return new Attributes();
    }

    /**
     * Create an instance of {@link Pipe }
     * 
     */
    public Pipe createPipe() {
        return new Pipe();
    }

    /**
     * Create an instance of {@link Info }
     * 
     */
    public Info createInfo() {
        return new Info();
    }

    /**
     * Create an instance of {@link Precond }
     * 
     */
    public Precond createPrecond() {
        return new Precond();
    }

    /**
     * Create an instance of {@link Title }
     * 
     */
    public Title createTitle() {
        return new Title();
    }

    /**
     * Create an instance of {@link Value }
     * 
     */
    public Value createValue() {
        return new Value();
    }

    /**
     * Create an instance of {@link Vlist }
     * 
     */
    public Vlist createVlist() {
        return new Vlist();
    }

    /**
     * Create an instance of {@link Scalemax }
     * 
     */
    public Scalemax createScalemax() {
        return new Scalemax();
    }

    /**
     * Create an instance of {@link Ctrl }
     * 
     */
    public Ctrl createCtrl() {
        return new Ctrl();
    }

    /**
     * Create an instance of {@link Filenames }
     * 
     */
    public Filenames createFilenames() {
        return new Filenames();
    }

    /**
     * Create an instance of {@link Name }
     * 
     */
    public Name createName() {
        return new Name();
    }

    /**
     * Create an instance of {@link Flist }
     * 
     */
    public Flist createFlist() {
        return new Flist();
    }

    /**
     * Create an instance of {@link Comment }
     * 
     */
    public Comment createComment() {
        return new Comment();
    }

    /**
     * Create an instance of {@link Description }
     * 
     */
    public Description createDescription() {
        return new Description();
    }

    /**
     * Create an instance of {@link Parametername }
     * 
     */
    public Parametername createParametername() {
        return new Parametername();
    }

    /**
     * Create an instance of {@link Parameter }
     * 
     */
    public Parameter createParameter() {
        return new Parameter();
    }

    /**
     * Create an instance of {@link Pipetype }
     * 
     */
    public Pipetype createPipetype() {
        return new Pipetype();
    }

    /**
     * Create an instance of {@link Seqtype }
     * 
     */
    public Seqtype createSeqtype() {
        return new Seqtype();
    }

    /**
     * Create an instance of {@link Authors }
     * 
     */
    public Authors createAuthors() {
        return new Authors();
    }

    /**
     * Create an instance of {@link Command }
     * 
     */
    public Command createCommand() {
        return new Command();
    }

    /**
     * Create an instance of {@link Paramfile }
     * 
     */
    public Paramfile createParamfile() {
        return new Paramfile();
    }

    /**
     * Create an instance of {@link Pise }
     * 
     */
    public Pise createPise() {
        return new Pise();
    }

    /**
     * Create an instance of {@link Separator }
     * 
     */
    public Separator createSeparator() {
        return new Separator();
    }

    /**
     * Create an instance of {@link Message }
     * 
     */
    public Message createMessage() {
        return new Message();
    }

    /**
     * Create an instance of {@link Group }
     * 
     */
    public Group createGroup() {
        return new Group();
    }

    /**
     * Create an instance of {@link Size }
     * 
     */
    public Size createSize() {
        return new Size();
    }

    /**
     * Create an instance of {@link Withpipe }
     * 
     */
    public Withpipe createWithpipe() {
        return new Withpipe();
    }

    /**
     * Create an instance of {@link Language }
     * 
     */
    public Language createLanguage() {
        return new Language();
    }

    /**
     * Create an instance of {@link Parameters }
     * 
     */
    public Parameters createParameters() {
        return new Parameters();
    }

    /**
     * Create an instance of {@link Seqfmt }
     * 
     */
    public Seqfmt createSeqfmt() {
        return new Seqfmt();
    }

    /**
     * Create an instance of {@link Paragraph }
     * 
     */
    public Paragraph createParagraph() {
        return new Paragraph();
    }

    /**
     * Create an instance of {@link Format }
     * 
     */
    public Format createFormat() {
        return new Format();
    }

    /**
     * Create an instance of {@link Reference }
     * 
     */
    public Reference createReference() {
        return new Reference();
    }

    /**
     * Create an instance of {@link Label }
     * 
     */
    public Label createLabel() {
        return new Label();
    }

    /**
     * Create an instance of {@link Scaleinc }
     * 
     */
    public Scaleinc createScaleinc() {
        return new Scaleinc();
    }

    /**
     * Create an instance of {@link Ctrls }
     * 
     */
    public Ctrls createCtrls() {
        return new Ctrls();
    }

    /**
     * Create an instance of {@link Category }
     * 
     */
    public Category createCategory() {
        return new Category();
    }

    /**
     * Create an instance of {@link Scalemin }
     * 
     */
    public Scalemin createScalemin() {
        return new Scalemin();
    }

    /**
     * Create an instance of {@link Code }
     * 
     */
    public Code createCode() {
        return new Code();
    }

    /**
     * Create an instance of {@link Doclink }
     * 
     */
    public Doclink createDoclink() {
        return new Doclink();
    }

}
