//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.2-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.03.28 at 05:22:06 PM PDT 
//


package org.ngbw.pise.commandrenderer.pise;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence maxOccurs="unbounded">
 *         &lt;element ref="{}pipetype"/>
 *         &lt;sequence maxOccurs="unbounded">
 *           &lt;element ref="{}language"/>
 *           &lt;element ref="{}code"/>
 *         &lt;/sequence>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "pipetypeAndLanguageAndCode"
})
@XmlRootElement(name = "pipe")
public class Pipe {

    @XmlElements({
        @XmlElement(name = "language", required = true, type = Language.class),
        @XmlElement(name = "code", required = true, type = Code.class),
        @XmlElement(name = "pipetype", required = true, type = Pipetype.class)
    })
    protected List<Object> pipetypeAndLanguageAndCode;

    /**
     * Gets the value of the pipetypeAndLanguageAndCode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the pipetypeAndLanguageAndCode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPipetypeAndLanguageAndCode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Language }
     * {@link Code }
     * {@link Pipetype }
     * 
     * 
     */
    public List<Object> getPipetypeAndLanguageAndCode() {
        if (pipetypeAndLanguageAndCode == null) {
            pipetypeAndLanguageAndCode = new ArrayList<Object>();
        }
        return this.pipetypeAndLanguageAndCode;
    }

}
