package  org.ngbw.cipresrest.webresource;

import javax.ws.rs.core.Response;
import javax.ws.rs.ext.ExceptionMapper;
import javax.ws.rs.ext.Provider;
import javax.ws.rs.WebApplicationException;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

import org.ngbw.restdatatypes.ErrorData;

/*
	WebApplicationException is the type jersey throws internally for example for
	404 resource not found.  Without this WebApplicationExceptionmapper, html error messages, 
	generated by jersey, are returned. 

	This mapper is only called if the WebApplicationException doesn't have an entity body, eg
	if created with new WebApplicationException("string" or status).  However if we, or
	jersey creates a WebApplicationException and builds it with an entity body, it seems
	that this mapper isn't used.  Can't do anyting about cases where jersey may create
	a WebApplicationException with a text body, but we should never do that in our code.

	Thus client apps may need to be able to handle an occassional text, or html, not xml, response.
*/
@Provider
public class WebApplicationExceptionMapper implements ExceptionMapper<WebApplicationException> 
{
	@SuppressWarnings("unused")
	private static final Log log = LogFactory.getLog(WebApplicationExceptionMapper.class.getName());

	public Response toResponse(WebApplicationException e)
	{
		log.info(e.toString());
		/*
			note that this will throw an exception (I think) if entity() is passed
			a null string, and in that case tomcat throws a 500 with some html text.
			Also note, Throwable.toString is never null. Throwable.getMessage may be null.
		*/
		String display = e.getMessage();
		if (display == null)
		{
			display = "Bad Request";
		}
		return Response.
				status(e.getResponse().getStatus()).
				type("application/xml").
				entity(new ErrorData(e.toString(), display, ErrorData.BAD_INVOCATION)).
				build();
	}
}
