//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.2-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.03.27 at 09:51:27 AM PDT 
//


package org.ngbw.sdk.bioutils.blast.blastxml;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.ngbw.conversion.impl.blastxml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.ngbw.conversion.impl.blastxml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link HspPositive }
     * 
     */
    public HspPositive createHspPositive() {
        return new HspPositive();
    }

    /**
     * Create an instance of {@link Hit }
     * 
     */
    public Hit createHit() {
        return new Hit();
    }

    /**
     * Create an instance of {@link HspHseq }
     * 
     */
    public HspHseq createHspHseq() {
        return new HspHseq();
    }

    /**
     * Create an instance of {@link ParametersGapExtend }
     * 
     */
    public ParametersGapExtend createParametersGapExtend() {
        return new ParametersGapExtend();
    }

    /**
     * Create an instance of {@link BlastOutputQueryLen }
     * 
     */
    public BlastOutputQueryLen createBlastOutputQueryLen() {
        return new BlastOutputQueryLen();
    }

    /**
     * Create an instance of {@link BlastOutputIterations }
     * 
     */
    public BlastOutputIterations createBlastOutputIterations() {
        return new BlastOutputIterations();
    }

    /**
     * Create an instance of {@link ParametersExpect }
     * 
     */
    public ParametersExpect createParametersExpect() {
        return new ParametersExpect();
    }

    /**
     * Create an instance of {@link HspQseq }
     * 
     */
    public HspQseq createHspQseq() {
        return new HspQseq();
    }

    /**
     * Create an instance of {@link BlastOutputReference }
     * 
     */
    public BlastOutputReference createBlastOutputReference() {
        return new BlastOutputReference();
    }

    /**
     * Create an instance of {@link IterationStat }
     * 
     */
    public IterationStat createIterationStat() {
        return new IterationStat();
    }

    /**
     * Create an instance of {@link ParametersScMismatch }
     * 
     */
    public ParametersScMismatch createParametersScMismatch() {
        return new ParametersScMismatch();
    }

    /**
     * Create an instance of {@link HspScore }
     * 
     */
    public HspScore createHspScore() {
        return new HspScore();
    }

    /**
     * Create an instance of {@link HitId }
     * 
     */
    public HitId createHitId() {
        return new HitId();
    }

    /**
     * Create an instance of {@link IterationHits }
     * 
     */
    public IterationHits createIterationHits() {
        return new IterationHits();
    }

    /**
     * Create an instance of {@link HspQueryFrame }
     * 
     */
    public HspQueryFrame createHspQueryFrame() {
        return new HspQueryFrame();
    }

    /**
     * Create an instance of {@link HitDef }
     * 
     */
    public HitDef createHitDef() {
        return new HitDef();
    }

    /**
     * Create an instance of {@link HspAlignLen }
     * 
     */
    public HspAlignLen createHspAlignLen() {
        return new HspAlignLen();
    }

    /**
     * Create an instance of {@link HspHitFrame }
     * 
     */
    public HspHitFrame createHspHitFrame() {
        return new HspHitFrame();
    }

    /**
     * Create an instance of {@link Parameters }
     * 
     */
    public Parameters createParameters() {
        return new Parameters();
    }

    /**
     * Create an instance of {@link StatisticsDbNum }
     * 
     */
    public StatisticsDbNum createStatisticsDbNum() {
        return new StatisticsDbNum();
    }

    /**
     * Create an instance of {@link HitLen }
     * 
     */
    public HitLen createHitLen() {
        return new HitLen();
    }

    /**
     * Create an instance of {@link Hsp }
     * 
     */
    public Hsp createHsp() {
        return new Hsp();
    }

    /**
     * Create an instance of {@link HspBitScore }
     * 
     */
    public HspBitScore createHspBitScore() {
        return new HspBitScore();
    }

    /**
     * Create an instance of {@link StatisticsLambda }
     * 
     */
    public StatisticsLambda createStatisticsLambda() {
        return new StatisticsLambda();
    }

    /**
     * Create an instance of {@link HspIdentity }
     * 
     */
    public HspIdentity createHspIdentity() {
        return new HspIdentity();
    }

    /**
     * Create an instance of {@link Statistics }
     * 
     */
    public Statistics createStatistics() {
        return new Statistics();
    }

    /**
     * Create an instance of {@link ParametersGapOpen }
     * 
     */
    public ParametersGapOpen createParametersGapOpen() {
        return new ParametersGapOpen();
    }

    /**
     * Create an instance of {@link StatisticsEntropy }
     * 
     */
    public StatisticsEntropy createStatisticsEntropy() {
        return new StatisticsEntropy();
    }

    /**
     * Create an instance of {@link StatisticsEffSpace }
     * 
     */
    public StatisticsEffSpace createStatisticsEffSpace() {
        return new StatisticsEffSpace();
    }

    /**
     * Create an instance of {@link ParametersScMatch }
     * 
     */
    public ParametersScMatch createParametersScMatch() {
        return new ParametersScMatch();
    }

    /**
     * Create an instance of {@link BlastOutput }
     * 
     */
    public BlastOutput createBlastOutput() {
        return new BlastOutput();
    }

    /**
     * Create an instance of {@link BlastOutputVersion }
     * 
     */
    public BlastOutputVersion createBlastOutputVersion() {
        return new BlastOutputVersion();
    }

    /**
     * Create an instance of {@link BlastOutputQueryID }
     * 
     */
    public BlastOutputQueryID createBlastOutputQueryID() {
        return new BlastOutputQueryID();
    }

    /**
     * Create an instance of {@link HspHitFrom }
     * 
     */
    public HspHitFrom createHspHitFrom() {
        return new HspHitFrom();
    }

    /**
     * Create an instance of {@link BlastOutputProgram }
     * 
     */
    public BlastOutputProgram createBlastOutputProgram() {
        return new BlastOutputProgram();
    }

    /**
     * Create an instance of {@link HspMidline }
     * 
     */
    public HspMidline createHspMidline() {
        return new HspMidline();
    }

    /**
     * Create an instance of {@link HspQueryFrom }
     * 
     */
    public HspQueryFrom createHspQueryFrom() {
        return new HspQueryFrom();
    }

    /**
     * Create an instance of {@link HspHitTo }
     * 
     */
    public HspHitTo createHspHitTo() {
        return new HspHitTo();
    }

    /**
     * Create an instance of {@link StatisticsKappa }
     * 
     */
    public StatisticsKappa createStatisticsKappa() {
        return new StatisticsKappa();
    }

    /**
     * Create an instance of {@link Iteration }
     * 
     */
    public Iteration createIteration() {
        return new Iteration();
    }

    /**
     * Create an instance of {@link BlastOutputParam }
     * 
     */
    public BlastOutputParam createBlastOutputParam() {
        return new BlastOutputParam();
    }

    /**
     * Create an instance of {@link HitNum }
     * 
     */
    public HitNum createHitNum() {
        return new HitNum();
    }

    /**
     * Create an instance of {@link HitAccession }
     * 
     */
    public HitAccession createHitAccession() {
        return new HitAccession();
    }

    /**
     * Create an instance of {@link IterationIterNum }
     * 
     */
    public IterationIterNum createIterationIterNum() {
        return new IterationIterNum();
    }

    /**
     * Create an instance of {@link ParametersFilter }
     * 
     */
    public ParametersFilter createParametersFilter() {
        return new ParametersFilter();
    }

    /**
     * Create an instance of {@link StatisticsHspLen }
     * 
     */
    public StatisticsHspLen createStatisticsHspLen() {
        return new StatisticsHspLen();
    }

    /**
     * Create an instance of {@link HspEvalue }
     * 
     */
    public HspEvalue createHspEvalue() {
        return new HspEvalue();
    }

    /**
     * Create an instance of {@link StatisticsDbLen }
     * 
     */
    public StatisticsDbLen createStatisticsDbLen() {
        return new StatisticsDbLen();
    }

    /**
     * Create an instance of {@link HspNum }
     * 
     */
    public HspNum createHspNum() {
        return new HspNum();
    }

    /**
     * Create an instance of {@link HitHsps }
     * 
     */
    public HitHsps createHitHsps() {
        return new HitHsps();
    }

    /**
     * Create an instance of {@link HspQueryTo }
     * 
     */
    public HspQueryTo createHspQueryTo() {
        return new HspQueryTo();
    }

    /**
     * Create an instance of {@link BlastOutputDb }
     * 
     */
    public BlastOutputDb createBlastOutputDb() {
        return new BlastOutputDb();
    }

    /**
     * Create an instance of {@link BlastOutputQueryDef }
     * 
     */
    public BlastOutputQueryDef createBlastOutputQueryDef() {
        return new BlastOutputQueryDef();
    }

}
