//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.2-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.03.27 at 09:51:27 AM PDT 
//
/**
 * Automatically generated classes by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation to unmarshall XML Blast output.
 */
@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.ngbw.org.sdk/conversion/blastxml", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.ngbw.sdk.bioutils.blast.blastxml;
