//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.2-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.03.27 at 09:51:27 AM PDT 
//


package org.ngbw.sdk.bioutils.blast.blastxml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.ngbw.org/conversion/impl/blastxml}Parameters_expect"/>
 *         &lt;element ref="{http://www.ngbw.org/conversion/impl/blastxml}Parameters_sc-match"/>
 *         &lt;element ref="{http://www.ngbw.org/conversion/impl/blastxml}Parameters_sc-mismatch"/>
 *         &lt;element ref="{http://www.ngbw.org/conversion/impl/blastxml}Parameters_gap-open"/>
 *         &lt;element ref="{http://www.ngbw.org/conversion/impl/blastxml}Parameters_gap-extend"/>
 *         &lt;element ref="{http://www.ngbw.org/conversion/impl/blastxml}Parameters_filter"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "parametersExpect",
    "parametersScMatch",
    "parametersScMismatch",
    "parametersGapOpen",
    "parametersGapExtend",
    "parametersFilter"
})
@XmlRootElement(name = "Parameters")
public class Parameters {

    @XmlElement(name = "Parameters_expect", required = true)
    protected ParametersExpect parametersExpect;
    @XmlElement(name = "Parameters_sc-match", required = true)
    protected ParametersScMatch parametersScMatch;
    @XmlElement(name = "Parameters_sc-mismatch", required = true)
    protected ParametersScMismatch parametersScMismatch;
    @XmlElement(name = "Parameters_gap-open", required = true)
    protected ParametersGapOpen parametersGapOpen;
    @XmlElement(name = "Parameters_gap-extend", required = true)
    protected ParametersGapExtend parametersGapExtend;
    @XmlElement(name = "Parameters_filter", required = true)
    protected ParametersFilter parametersFilter;

    /**
     * Gets the value of the parametersExpect property.
     * 
     * @return
     *     possible object is
     *     {@link ParametersExpect }
     *     
     */
    public ParametersExpect getParametersExpect() {
        return parametersExpect;
    }

    /**
     * Sets the value of the parametersExpect property.
     * 
     * @param value
     *     allowed object is
     *     {@link ParametersExpect }
     *     
     */
    public void setParametersExpect(ParametersExpect value) {
        this.parametersExpect = value;
    }

    /**
     * Gets the value of the parametersScMatch property.
     * 
     * @return
     *     possible object is
     *     {@link ParametersScMatch }
     *     
     */
    public ParametersScMatch getParametersScMatch() {
        return parametersScMatch;
    }

    /**
     * Sets the value of the parametersScMatch property.
     * 
     * @param value
     *     allowed object is
     *     {@link ParametersScMatch }
     *     
     */
    public void setParametersScMatch(ParametersScMatch value) {
        this.parametersScMatch = value;
    }

    /**
     * Gets the value of the parametersScMismatch property.
     * 
     * @return
     *     possible object is
     *     {@link ParametersScMismatch }
     *     
     */
    public ParametersScMismatch getParametersScMismatch() {
        return parametersScMismatch;
    }

    /**
     * Sets the value of the parametersScMismatch property.
     * 
     * @param value
     *     allowed object is
     *     {@link ParametersScMismatch }
     *     
     */
    public void setParametersScMismatch(ParametersScMismatch value) {
        this.parametersScMismatch = value;
    }

    /**
     * Gets the value of the parametersGapOpen property.
     * 
     * @return
     *     possible object is
     *     {@link ParametersGapOpen }
     *     
     */
    public ParametersGapOpen getParametersGapOpen() {
        return parametersGapOpen;
    }

    /**
     * Sets the value of the parametersGapOpen property.
     * 
     * @param value
     *     allowed object is
     *     {@link ParametersGapOpen }
     *     
     */
    public void setParametersGapOpen(ParametersGapOpen value) {
        this.parametersGapOpen = value;
    }

    /**
     * Gets the value of the parametersGapExtend property.
     * 
     * @return
     *     possible object is
     *     {@link ParametersGapExtend }
     *     
     */
    public ParametersGapExtend getParametersGapExtend() {
        return parametersGapExtend;
    }

    /**
     * Sets the value of the parametersGapExtend property.
     * 
     * @param value
     *     allowed object is
     *     {@link ParametersGapExtend }
     *     
     */
    public void setParametersGapExtend(ParametersGapExtend value) {
        this.parametersGapExtend = value;
    }

    /**
     * Gets the value of the parametersFilter property.
     * 
     * @return
     *     possible object is
     *     {@link ParametersFilter }
     *     
     */
    public ParametersFilter getParametersFilter() {
        return parametersFilter;
    }

    /**
     * Sets the value of the parametersFilter property.
     * 
     * @param value
     *     allowed object is
     *     {@link ParametersFilter }
     *     
     */
    public void setParametersFilter(ParametersFilter value) {
        this.parametersFilter = value;
    }

}
